"""On-disk cache of decoded matrices, so re-opening one is near-instant.

HDTV caches PROJECTIONS beside the matrix file (.prx/.pry, generated by
MatOp::Project and reused if present). A literal port would help us
little: HDTV never holds the matrix in memory, so projections are what it
would otherwise recompute, whereas we do hold it -- projections cost
milliseconds off a resident array and the real expense is the decode
itself, measured at about 4.9 s for the reference .mtx after the v3.1.1
work. So the DECODED ARRAY is what gets cached here.

Two deliberate differences from HDTV beyond that:

  * Files go in a cache directory, not beside the user's data. Writing
    sidecars into the directory a user keeps their measurements in is
    presumptuous, and it makes their backups larger for no reason they
    chose.
  * The cache is keyed on the source's identity AND its modification time
    and size, so editing or replacing a matrix can never serve a stale
    array. A path alone would.

No transpose cache (HDTV's .tmtx): that only pays off when cuts stream
from disk, and ours run against a resident array where both axes are
equally reachable.
"""

import hashlib
import os
import tempfile

import numpy as np

# Roughly two reference matrices. Small enough not to surprise anyone
# looking at their disk, large enough that alternating between two
# matrices -- the case this exists for -- keeps both.
MAX_CACHE_BYTES = 1_200_000_000


#: Overrides the location entirely. Set it to a scratch directory to keep
#: a test run out of the real cache -- which the suite's conftest does for
#: every test, because a test that patches load_mtx would otherwise be
#: silently satisfied by a cache entry an earlier test wrote, and because
#: no test should leave hundreds of megabytes in a developer's profile.
CACHE_DIR_ENV = "SPECTRATOOLS_MATRIX_CACHE"


def cache_dir():
    """Where cached arrays live. Under the user's local app data on
    Windows, XDG_CACHE_HOME (or ~/.cache) elsewhere, matching what each
    platform expects a discardable cache to sit in."""
    override = os.environ.get(CACHE_DIR_ENV)
    if override:
        return override
    base = os.environ.get("LOCALAPPDATA")
    if not base:
        base = os.environ.get("XDG_CACHE_HOME") or os.path.join(
            os.path.expanduser("~"), ".cache"
        )
    return os.path.join(base, "SpectraTools", "matrix-cache")


def _key(path):
    """Identity of the SOURCE file: absolute path, size and mtime.

    All three matter. Path alone would serve a stale array after the file
    is regenerated in place, which is exactly what happens to someone
    re-sorting a matrix from the same run and is the failure that would
    look like the program ignoring their new data.
    """
    stat = os.stat(path)
    material = f"{os.path.abspath(path)}|{stat.st_size}|{stat.st_mtime_ns}"
    return hashlib.sha256(material.encode("utf-8")).hexdigest()[:32]


def cached_path(path):
    return os.path.join(cache_dir(), f"{_key(path)}.npy")


def load(path):
    """The cached array for `path`, or None on any miss.

    Never raises: a cache is an optimisation, and every failure mode here
    -- absent file, unreadable directory, truncated .npy from a previous
    crash, a source file that has since been deleted -- has the same
    correct answer, which is to decode from source instead.
    """
    try:
        target = cached_path(path)
        if not os.path.exists(target):
            return None
        matrix = np.load(target, allow_pickle=False)
    except Exception:
        return None
    if matrix.ndim != 2:
        return None
    try:
        # Stamp recency explicitly. The prune sorts by st_atime, but NTFS
        # last-access updates are disabled or lazily batched on many
        # Windows systems, so reads alone may never refresh it -- degrading
        # "least recently USED" to "oldest CREATED", which evicts exactly
        # the daily-driver matrix the cache exists for. utime sets both
        # atime and mtime to now, portably. Best-effort like everything
        # else here: a hit that cannot be stamped is still a hit.
        os.utime(target)
    except OSError:
        pass
    return matrix


def store(path, matrix):
    """Caches `matrix` as the decoded form of `path`. Returns True if it
    was written.

    Written to a temporary file in the same directory and then moved into
    place, so an interrupted write cannot leave a half-written array that
    a later run would load as real data. Failures are swallowed for the
    same reason as in load(): a cache that cannot be written is not an
    error the user needs to hear about.
    """
    try:
        directory = cache_dir()
        os.makedirs(directory, exist_ok=True)
        target = cached_path(path)
        descriptor, temporary = tempfile.mkstemp(dir=directory, suffix=".tmp")
        try:
            # Written through the OPEN HANDLE rather than by name. np.save
            # appends ".npy" to a name that lacks it, so passing the
            # temporary's name wrote the array to "<temp>.tmp.npy" while
            # mkstemp's own empty "<temp>.tmp" still existed -- and the
            # move then promoted the EMPTY file to the cache entry and
            # orphaned the real one. Handing it a file object writes
            # exactly where told, with no name rewriting to reason about.
            with os.fdopen(descriptor, "wb") as handle:
                np.save(handle, matrix, allow_pickle=False)
            os.replace(temporary, target)
        except Exception:
            try:
                os.remove(temporary)
            except OSError:
                pass
            return False
        prune(directory)
        return True
    except Exception:
        return False


def prune(directory=None, limit=MAX_CACHE_BYTES):
    """Drops the least recently used entries until the cache fits.

    Without this the cache grows without bound -- every matrix a user ever
    opens, at hundreds of megabytes each. Least-recently-USED rather than
    oldest-written, so a matrix opened daily is not evicted just because
    it was first cached a long time ago.
    """
    directory = directory or cache_dir()
    try:
        entries = []
        total = 0
        for name in os.listdir(directory):
            if not name.endswith(".npy"):
                continue
            full = os.path.join(directory, name)
            try:
                stat = os.stat(full)
            except OSError:
                continue
            entries.append((stat.st_atime, stat.st_size, full))
            total += stat.st_size
        entries.sort()
        while total > limit and entries:
            _, size, full = entries.pop(0)
            try:
                os.remove(full)
                total -= size
            except OSError:
                break
        return total
    except Exception:
        return 0
